refactor login
Signed-off-by: Felix Bartels <felix@host-consultants.de>

diff --git a/bin/codimd b/bin/codimd
--- a/bin/codimd
+++ b/bin/codimd
@@ -85,21 +85,6 @@ function export_note() {
 CODIMD_COOKIES_FILE=${CODIMD_COOKIES_FILE:="$CONFIG_DIR/key.conf"}
 
 function authenticate_email() {
-    if [[ -z $1 ]]; then
-        echo "ERROR: You must provide an email and password."
-        echo ""
-        echo "Usage: codimd login --email <email> <password>"
-        echo "For usage examples, see: $codi_cli help"
-        exit 1
-    fi
-
-    PASSWORD=$2
-
-    if [[ -z $2 ]]; then
-        echo "Enter your password"
-        read -s PASSWORD
-    fi
-
     curl -c $CODIMD_COOKIES_FILE \
         -XPOST \
         --data-urlencode "email=$1" --data-urlencode "password=$PASSWORD" \
@@ -107,14 +92,6 @@ function authenticate_email() {
 }
 
 function authenticate_ldap() {
-    if [[ -z $1 ]] || [[ -z $2 ]]; then
-        echo "ERROR: You must provide an email and password."
-        echo ""
-        echo "Usage: codimd login --ldap <username> <password>"
-        echo "For usage examples, see: $codi_cli help"
-        exit 1
-    fi
-
     curl -c $CODIMD_COOKIES_FILE \
         -XPOST \
         --data-urlencode "email=$1" --data-urlencode "password=$2" \
@@ -122,25 +99,33 @@ function authenticate_ldap() {
 }
 
 function authenticate() {
-    if [[ -z $1 ]]; then
-        echo "Usage: codimd login [--email|--ldap]"
-        echo "For usage examples, see: $codi_cli help"
-        exit 0
-    fi
+    method=${1:-"undefined"}
 
-    if [[ $1 == "--email" ]]; then
-        shift
-        authenticate_email "$@"
-    elif [[ $1 == "--ldap" ]]; then
-        shift
-        authenticate_ldap "$@"
-    else
-        echo "ERROR: You must provide a protocol."
+    # when method, login and password are defined we expect three parameters here
+    if [[ "$#" -ne 3 ]]; then
+        echo "ERROR: You must provide a login and a password."
         echo ""
-        echo "Usage: codimd login [--email|--ldap] <login> <password>"
+        echo "Usage: codimd login [--email|--ldap] <username> <password>"
         echo "For usage examples, see: $codi_cli help"
         exit 1
     fi
+
+    case "$method" in
+    --email)
+        shift
+        authenticate_email "$@"
+        ;;
+    --ldap)
+        shift
+        authenticate_ldap "$@"
+        ;;
+    *)
+        echo "ERROR: You must provide a valid login method."
+        echo "Usage: codimd login [--email|--ldap] <login> <password>"
+        echo "For usage examples, see: $codi_cli help"
+        exit 1
+        ;;
+    esac
 
     if [[ $(is_authenticated) == "ok" ]]; then
         echo "Logged in $CODIMD_SERVER as $1 successfully."
