feat (auth & history): Add support for authentification and history

diff --git a/bin/codimd b/bin/codimd
--- a/bin/codimd
+++ b/bin/codimd
@@ -16,6 +16,15 @@ Options:
     $ $codi_cli export --html qhmNmwmxSmK1H2oJmkKBQQ output.html
     $ $codi_cli export --slides qhmNmwmxSmK1H2oJmkKBQQ output.zip
 
+    $ $codi_cli login email@example.net p4sW0rD
+    $ $codi_cli profile
+    You are logged in as email with id x[...]x.
+    $ $codi_cli history
+    ID                      Name
+    0nAp3YRyTlyQ-N3N7lCk-w  Note_1
+    qhmNmwmxSmK1H2oJmkKBQQ  Note_2
+    $ $codi_cli logout
+
 Example:
     $ env CODIMD_SERVER='https://codimd.example.com' $codi_cli import /path/to/your/content.md
 "
@@ -53,12 +62,79 @@ function export_note() {
     fi
 }
 
+CODIMD_COOKIES_FILE=${CODIMD_COOKIES_FILE:="/tmp/codimd-cookies.txt"}
+
+function authentificate() {
+    if [[ -z $1 ]] || [[ -z $2 ]]; then
+        echo "ERROR: You must provide an email and password."
+        echo ""
+        echo "Usage: codimd login <email> <password>"
+        echo "For usage examples, see: codimd help"
+        exit 1
+    fi
+
+    curl -c $CODIMD_COOKIES_FILE \
+        -XPOST \
+        -d "email=$1&password=$2" \
+        $CODIMD_SERVER/login &>/dev/null
+
+    if [[ $(is_authentificated) ]]; then
+        echo "Logged in $CODIMD_SERVER as $1 successfully."
+    else
+        echo "Invalid email or password."
+        exit 1
+    fi
+}
+
+function is_authentificated() {
+    STATUS=$(curl -b $CODIMD_COOKIES_FILE $CODIMD_SERVER/me 2>/dev/null)
+
+    [ "$(echo $STATUS | jq -r '.status')" == "ok" ] ; echo $?
+}
+
+function logout() {
+    curl -b $CODIMD_COOKIES_FILE -c $CODIMD_COOKIES_FILE $CODIMD_SERVER/logout &>/dev/null
+}
+
+function get_profile() {
+    STATUS=$(curl -b $CODIMD_COOKIES_FILE $CODIMD_SERVER/me 2>/dev/null)
+
+    if [[ "$(echo $STATUS | jq -r '.status')" == "forbidden" ]]; then
+        echo "Error: Need to authentificate."
+        exit 1
+    else
+        NAME=$(echo $STATUS | jq -r '.name')
+        ID=$(echo $STATUS | jq -r '.id')
+        echo "You are logged in as $NAME with id $ID."
+    fi
+}
+
+function get_history() {
+    if [[ "$(is_authentificated)" ]]; then
+        HISTORY=$(curl -b $CODIMD_COOKIES_FILE $CODIMD_SERVER/history 2>/dev/null)
+        echo $HISTORY | jq -r '["ID", "", "", "Name"], (.history[] | [.id, .text]) | @tsv'
+        # If the tags are needed, they can be found in .tags
+        # Same for the date in .time
+    else
+        echo "Error: Need to authentificate."
+        exit 1
+    fi
+}
+
 if [[ "$1" == "import" ]]; then
     import_note "$2"
 elif [[ "$1" == "publish" ]]; then
     publish_note "$2"
 elif [[ "$1" == "export" ]]; then
     export_note "$2" "$3" "$4"
+elif [[ "$1" == "login" ]]; then
+    authentificate "$2" "$3"
+elif [[ "$1" == "logout" ]]; then
+    logout
+elif [[ "$1" == "profile" ]]; then
+    get_profile
+elif [[ "$1" == "history" ]]; then
+    get_history
 else
     echo "$help_str"
 fi
