Updated help menu and example for info command Add json format option to info command Fixed issue with returning all parts of the metadata
Signed-off-by: Dark Decoy <darkdecoy@notracking.space>

diff --git a/bin/hedgedoc b/bin/hedgedoc
--- a/bin/hedgedoc
+++ b/bin/hedgedoc
@@ -76,6 +76,9 @@ Commands:
     info <note_id> [--json]
         View the metadata for a given note on the server.
 
+    info <note_id> [--json]
+        View the metadata for a given note on the server.
+
 Config:
     Configuration is set via environment variables (e.g. in ~/.bashrc or shell).
 
@@ -187,6 +190,15 @@ function import_note() {
 
 function info_note() {
     local note_id="$1"
+    local json="$2"
+
+    if [[ ! "$note_id" ]]; then
+        echo "Error: You must specify an export type and note id to export." >&2
+        echo "" >&2
+        echo "Usage: $SCRIPTNAME info <note_id> [--json]" >&2
+        echo "For usage exmaples, see: $SCRIPTNAME help" >&2
+        return 2
+    fi
 <<<<<<< HEAD
     local json="$2"
 
@@ -197,6 +209,14 @@ function info_note() {
         echo "For usage exmaples, see: $SCRIPTNAME help" >&2
         return 2
     fi
+
+    if [[ "$json" == "--json" ]]
+    then
+
+        curl \
+            --silent \
+            --cookie "$HEDGEDOC_COOKIES_FILE" \
+            "${HEDGEDOC_SERVER}/$note_id/info"
 
     if [[ "$json" == "--json" ]]
     then
@@ -234,43 +254,6 @@ function info_note() {
         echo ${metadata[@]}
 
     fi
-=======
-
-    if [[ "$json" == "--json" ]]
-    then
-
-        curl \
-            --silent \
-            --cookie "$HEDGEDOC_COOKIES_FILE" \
-            "${HEDGEDOC_SERVER}/$note_id/info"
-
-    else
-
-        response="$(
-            curl \
-                --silent \
-                --cookie "$HEDGEDOC_COOKIES_FILE" \
-                "${HEDGEDOC_SERVER}/$note_id/info" \
-            | jq '.title, .description, .viewcount, .createtime, .updatetime')
-        )"
-    
-        SAVEIFS=$IFS
-        IFS=$'\n'
-        metadata=( $response )
-        IFS=$SAVEIFS
-
-        for ((i=0; i<${#metadata[@]}; i++))
-        do
-            
-            temp=${metadata[$i]}
-            temp=${temp// /-}
-
-            metadata[$i]=${temp//\"/ }
-
-        done
-
-    echo $metadata
->>>>>>> a371d79 (Added getting metadata from a note id)
 
 }
 
@@ -490,11 +473,7 @@ function main() {
             return 0
             ;;
         info)
-<<<<<<< HEAD
             info_note "${1:-}" "${2:-}"
-=======
-            info_note "${1:-}"
->>>>>>> a371d79 (Added getting metadata from a note id)
             ;;
         import|import-as)
             import_note "${1:-}" "${2:-}"
